version: '3'

services:
  distributed-system-app-1:
    image: distributed-system
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - DB_URL=jdbc:mariadb://db:3306/local
      - DB_USER=junseok
      - DB_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=mypassword
    depends_on:
      - redis
      - db
    networks:
      - distributed_network

  distributed-system-app-2:
    image: distributed-system
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - DB_URL=jdbc:mariadb://db:3306/local
      - DB_USER=junseok
      - DB_PASSWORD=1234
    depends_on:
      - redis
      - db
    networks:
      - distributed_network

  distributed-system-app-3:
    image: distributed-system
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9002:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - DB_URL=jdbc:mariadb://db:3306/local
      - DB_USER=junseok
      - DB_PASSWORD=1234
    depends_on:
      - redis
      - db
    networks:
      - distributed_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - distributed_network

  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=local
      - MYSQL_USER=junseok
      - MYSQL_PASSWORD=1234
    command:
      - "--default-authentication-plugin=sha256_password"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - distributed_network

volumes:
  mariadb:

networks:
  distributed_network: