server:
  port: 1234
spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/mydb}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379


