server:
  port: 1234
spring:
#  datasource:
#    url: ${DB_URL:jdbc:mariadb://localhost:3306/local}
#    username: ${DB_USER:root}
#    password: ${DB_PASSWORD:1234}
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379